### ISSUE TITLE
oder of concatenation

### ISSUE THREAD

**Issue by habelson** [erhudy/chef-concat#1]
hi,

I am trying to use your cookbook, but in my case, order matters. I have 2 fragments, a top and a bottom, and no matter which order I specify the fragments in my recipe, they are written in the wrong order. any ideas?

**Comment by erhudy** [comment]
Can you post the resources you're using?

**Comment by habelson** [comment]
looking in the code, I see that the fragments are concatenated in their lexical order by name. I also saw that I could use an "order" property to get them to order correctly. Might be worth adding to the docs. The current README seems to imply that they are concatenated in the order they are defined.

**Comment by erhudy** [comment]
Yeah, use `order` to add a string that will be prepended to force a particular lexical sort (e.g., `001` and `002`). I will update the readme to list out all attributes and document their use cases.
